### ISSUE TITLE
Incompatible with trashslot mod

### ISSUE THREAD

**Issue by whitestarx0312** [cpw/inventorysorter#11]
I get this crash when I do an inventory sort with the mod Inventory Tweaks. This happened in 1.8 but has returned in 1.9.

Forge: forge-12.16.0.1804
InvTweaks: InventoryTweaks-1.61-dev-44
InvSorter: inventorysorter-1.9-0.7.8+28

http://pastebin.com/DWUNRnzq
*I can upload the full log if needed.

**Comment by whitestarx0312** [comment]
Just for reference, here is the same crash in 1.8.9.
http://pastebin.com/BKHM6z60

**Comment by cpw** [comment]
Should be fixed with recent builds.

**Comment by whitestarx0312** [comment]
Still having this issue with:
Forge: forge-12.16.0.1865
InvSorter: inventorysorter-1.9-0.7.12+30

http://pastebin.com/wBGhce6m

**Comment by cpw** [comment]
What's being sorted? I can't reproduce..

**Comment by whitestarx0312** [comment]
I'm not really sorting anything, I just open my inventory and middleclick (usually on accident) and it freezes up until I manually kill the program. Here is my inventory right before I crash:
http://imgur.com/EXepgJM

**Comment by cpw** [comment]
That doesn't look like a standard inventory..

**Comment by whitestarx0312** [comment]
Ah, the chest icon is from Quark (http://minecraft.curseforge.com/projects/quark?gameCategorySlug=mc-mods&projectID=243121) and the bottom slot is from Trashslot (http://minecraft.curseforge.com/projects/trashslot?gameCategorySlug=mc-mods&projectID=235577)

**Comment by cpw** [comment]
Remove trashslot. Does it work?

**Comment by whitestarx0312** [comment]
Yep that worked.

**Comment by cpw** [comment]
OK. I'll take a look at trashslot, see what he's doing that's funky..

**Comment by cpw** [comment]
Could you try with inventorysorter-1.9-0.7.13+31.jar please? I rewrote a lot of the slot detection and handling, it may not be crashy any more. If it still doesn't work, please share a link to the mod download you're using.

**Comment by whitestarx0312** [comment]
Hmm still crashes upon middle clicking in game. Here is the full latest log (https://www.dropbox.com/s/bymv0z2xsjo2fb0/fml-client-latest.log?dl=0) 

Trashslot: http://minecraft.curseforge.com/projects/trashslot/files/2289840
Inventory Sorter: http://minecraft.curseforge.com/projects/inventory-sorter/files/2297068
I just updated to the recommended version of forge as well.

**Comment by cpw** [comment]
Thanks for checking!

**Comment by whitestarx0312** [comment]
Thank you for continuing to look into it!

**Comment by whitestarx0312** [comment]
Upon middle clicking with the new version (inventorysorter-1.9-0.7.14+32), I no longer crash but I get a fatal error and the world closes.
Pastebin: http://pastebin.com/aF2qHkbT

**Comment by WenXin20** [comment]
I get the same problem with the Trash Slot Mod and with the Rucksacks mod, but in 1.8.9

**Comment by whitestarx0312** [comment]
Seems to be fixed in the latest version of Trashslot and Inventory sorter on 1.10.2.
